USE master;
GO


IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'shoesshop')
BEGIN 
	ALTER DATABASE shoesshop SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE shoesshop;
END
GO

create database shoesshop;
go

use shoesshop;
go

--TẠO BẢNG
CREATE TABLE HANG(
	MAHANG VARCHAR(10) PRIMARY KEY,
	TENHANG NVARCHAR(30) NOT NULL
);
GO

CREATE TABLE SANPHAM(
	MASP VARCHAR(10) PRIMARY KEY,
	TENSP NVARCHAR(50) NOT NULL,
	MAHANG VARCHAR(10),
	PHAI INT NOT NULL,
	SOLUONG INT NOT NULL,
	DONGIA REAL NOT NULL,
	NGAYNHAP DATE NOT NULL
);
GO

CREATE TABLE NGUOIDUNG(
	MAND VARCHAR(10) PRIMARY KEY,
	TENND NVARCHAR(50) NOT NULL,
	PHAI INT NOT NULL,
	NGAYSINH DATE,
	TENTK VARCHAR(100) NOT NULL,
	MATKHAU NVARCHAR(32) NOT NULL,
	CHUCVU INT NOT NULL
);
GO

CREATE TABLE DONHANG(
	MADH VARCHAR(10) PRIMARY KEY,
	MAND VARCHAR(10),
	NGAYDATHANG DATE NOT NULL,
	MASP VARCHAR(10),
	SOLUONGSP INT NOT NULL,
	TONGTIEN REAL NOT NULL,
	TINHTRANG INT NOT NULL
);
GO

--KHÓA NGOẠI
ALTER TABLE SANPHAM
ADD CONSTRAINT SP_HANG FOREIGN KEY (MAHANG) REFERENCES HANG (MAHANG)
go

ALTER TABLE DONHANG
ADD CONSTRAINT KH_NGUOIDUNG FOREIGN KEY (MAND) REFERENCES NGUOIDUNG (MAND)
go

ALTER TABLE DONHANG
ADD CONSTRAINT KH_SP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
go

-- view 
CREATE VIEW v_thongtingnuoidung AS
	SELECT u.MAND,u.TENND,u.PHAI,u.NGAYSINH,u.TENTK,u.CHUCVU FROM NGUOIDUNG u;
go

-- procedure
--thủ tục đăng ký tài khoản
CREATE PROCEDURE p_dangky (@maND VARCHAR(10), 
						   @tenND NVARCHAR(50), 
						   @phai INT, 
						   @ngaySinh DATE, 
						   @tenTK VARCHAR(100), 
						   @matKhau VARCHAR(32))
as
begin
	insert into NGUOIDUNG VALUES(@maND, @tenND, @phai, @ngaySinh, @tenTK, @matKhau, 0);
end;
go

CREATE PROCEDURE p_thongtinnguoidung (@username VARCHAR(100))
AS 
	SELECT * FROM v_thongtingnuoidung v WHERE v.TENTK = @username;
go

insert into NGUOIDUNG VALUES('001', N'Admin', 0,null,'admin', '123456', 1);


